#!/bin/sh

case "$1" in
	start)
		echo "Post initialize ..."
		# Start up lo interface
		/sbin/ifconfig lo 127.0.0.1 up >/dev/null 2>&1
		# Re-init audio system
		echo 1 > /sys/bus/i2c/devices/2-0013/init_chip
		echo 1 > /sys/bus/i2c/devices/2-0013/audio_sel
		echo 0 > /sys/bus/i2c/devices/2-0030/volume
		# Enable audio codec
		/usr/bin/amixer cset numid=20,iface=MIXER,name='Line Out Source Playback Route' 0 >/dev/null 2>&1
		/usr/bin/amixer cset numid=3,iface=MIXER,name='Line Out Playback Volume' 100 >/dev/null 2>&1
		/usr/bin/amixer cset numid=4,iface=MIXER,name='Line Out Playback Switch' on >/dev/null 2>&1
		/usr/bin/amixer cset numid=1,iface=MIXER,name='DAC Playback Volume' 100 >/dev/null 2>&1
		/usr/bin/amixer cset numid=10,iface=MIXER,name='DAC Playback Switch' on >/dev/null 2>&1
		echo 0 > /sys/bus/i2c/devices/2-0030/volume
		/bin/playzero &
		sleep 1
		/usr/bin/aplay /usr/share/voice_hints/startup.wav >/dev/null 2>&1
		# Power-on LTE module
		echo 1 > /sys/bus/i2c/devices/2-0030/lte_power
		sleep 0.2
		# Power-on wlan card
		echo 1 > /sys/bus/i2c/devices/2-0030/wlan_power
		# Shutdown all leds
		echo 0 > /sys/bus/i2c/devices/2-0030/led_eth
		echo 0 > /sys/bus/i2c/devices/2-0030/led_wifi
		echo 0 > /sys/bus/i2c/devices/2-0030/led_lte
		echo 0 > /sys/bus/i2c/devices/2-0030/led_bt
		echo 0 > /sys/bus/i2c/devices/2-0030/led_jack
		# Re-init audio system
		sleep 0.2
		echo 1 > /sys/bus/i2c/devices/2-0030/amp_init
		sleep 0.2
		echo 45 > /sys/bus/i2c/devices/2-0030/volume
		;;
	stop)
		;;
	restart|reload)
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
