#!/bin/sh

case "$1" in
	start)
		printf "Starting hl_agent: "
		# start main program.
		sleep 3
		CURR_DIR=`pwd`
		cd /app/hl_agent;
		if [ -d /app/hl_agent/logs ]; then
			./bin/hl_lua ./lua/hl_agent.lua lte >>/app/hl_agent/logs/hl_agent.log 2>&1 &
		else
			./bin/hl_lua ./lua/hl_agent.lua lte >/dev/null 2>&1 &
		fi
		if ! ps -ef | grep hl_dog.sh | grep -v grep; then
			./bin/hl_dog.sh &
		fi
		cd $CURR_DIR
		echo "OK"
		;;
	stop)
		printf "Stopping hl_agent: "
		killall -w -9 hl_dog.sh >/dev/null 2>&1
		killall -w -9 hl_lua >/dev/null 2>&1
		echo "OK"
		;;
	restart|reload)
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
