#!/bin/sh

case "$1" in
	start)
		printf "Starting sysmanager: "
		# Start hl_sysmanager daemon
		/app/bin/FactoryTest &
		;;
	stop)
		;;
	restart|reload)
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
