#!/bin/sh

echo "INIT: Proceed startup sequence"

# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
echo "INIT: Begin system initialize"
export PATH=/bin:/sbin:/usr/bin:/usr/sbin
for i in /etc/init.d/S??* ;do

    # Ignore dangling symlinks (if any).
    [ ! -f "$i" ] && continue

    case "$i" in
	*)
	    $i start
	    ;;
    esac
done

# Start all init scripts in /app/etc/init.d
# executing them in numerical order.
#
echo "INIT: Begin application initialize"
export PATH=$PATH:/app/bin:/app/sbin
#
for i in /app/etc/init.d/S??* ;do

    # Ignore dangling symlinks (if any).
    [ ! -f "$i" ] && continue

    case "$i" in
    *)
        $i start
        ;;
    esac
done

echo "INIT: Succeed"
