#!/bin/sh

case "$1" in
	start)
		echo "Prepare base filesystem ..."

		# Extract ramfs
		/bin/tar -xf /usr/share/rofs/var.tar.gz -C /var/ >/dev/null 2>&1
		/bin/tar -xf /usr/share/rofs/ssh.tar.gz -C /etc/ssh/ >/dev/null 2>&1

		# Mount boot partition
		/bin/mount -n -o ro /dev/mmcblk0p1 /boot

		# Resize app partition
		if [ ! -f /boot/app_part.resized ]; then
			echo "Resize app partition ..."
			/usr/sbin/parted -s /dev/mmcblk0 unit % resizepart 3 100
			/sbin/resize2fs -f /dev/mmcblk0p3
			/sbin/mkfs.ext4 -F -L app /dev/mmcblk0p3
			/bin/mount -n -o remount,rw /dev/mmcblk0p1 /boot
			echo "1" > /boot/app_part.resized
			/bin/sync
			/bin/mount -n -o remount,ro /dev/mmcblk0p1 /boot
		fi

		# Mount app partition
		/sbin/fsck.ext4 -p /dev/mmcblk0p3
		/bin/mount -n -o defaults /dev/mmcblk0p3 /app
		;;
	stop)
		echo "Safely umount partitions ..."
		/bin/sync
		/bin/umount -r /dev/mmcblk0p3
		/bin/umount -r /dev/mmcblk0p1
		;;
	restart|reload)
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
