#!/bin/sh

case "$1" in
	start)
        if [ ! -f /app/userapps.done ]; then
            echo "Prepare for rtm user mode ..."
            rm -fr /app/* >/dev/null 2>&1
            if [ -f /usr/share/rtmfs/userapp.tar.gz ]; then
                /bin/tar -xf /usr/share/rtmfs/userapp.tar.gz -C /app/ >/dev/null 2>&1
                echo "1" > /app/userapps.done
                /bin/sync
            fi
        fi
		;;
	stop)
		;;
	restart|reload)
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
