#!/bin/sh

case "$1" in
	start)
		echo "Post initialize ..."
		# Start up lo interface
		/sbin/ifconfig lo 127.0.0.1 up >/dev/null 2>&1
		# Enable audio codec
		/usr/bin/amixer cset numid=20,iface=MIXER,name='Line Out Source Playback Route' 0 >/dev/null 2>&1
		/usr/bin/amixer cset numid=3,iface=MIXER,name='Line Out Playback Volume' 100 >/dev/null 2>&1
		/usr/bin/amixer cset numid=4,iface=MIXER,name='Line Out Playback Switch' on >/dev/null 2>&1
		/usr/bin/amixer cset numid=1,iface=MIXER,name='DAC Playback Volume' 100 >/dev/null 2>&1
		/usr/bin/amixer cset numid=10,iface=MIXER,name='DAC Playback Switch' on >/dev/null 2>&1
		/bin/playzero &
		;;
	stop)
		;;
	restart|reload)
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
